### ISSUE TITLE
 LOG  response {"code": "access_key_not_found", "message": "Key không tìm thấy"}

### ISSUE THREAD

**Issue by tonynhox** [map4d/map4d-services-react-native#3]
thư viện này còn hoạt động không, tôi đã cấp key ở AndroidManifest rồi, thư viện "react-native-map4d-map" hoạt động vẫn tốt, nhưng thư viện này lại bảo không tìm thấy key.

**Comment by omyto** [comment]
Hi @tonynhox,
Nhờ bạn kiểm tra lại xem có phải cung cấp key với `android:name` là `vn.map4d.services.ACCESS_KEY` hay không?
Ngoài ra key đó có tick chọn [loại dịch vụ](https://map.map4d.vn/developer/key) là địa điểm và tìm đường chưa

**Comment by tonynhox** [comment]
mình cảm ơn được rồi ạ, do bên doc ghi là vn.map4d.map.ACCESS_KEY chứ không phải vn.map4d.services.ACCESS_KEY

**Comment by omyto** [comment]
Á, sorry bạn.
Bên mình sẽ update lại tài liệu. Mình xin phép close issue
